name=MSS-XCADE Control Library
version=1.0.1
author=Nathan Holmes <support@iascaled.com>
maintainer=Nathan Holmes <support@iascaled.com>
sentence=A library for controlling the Iowa Scaled Engineering MSS-XCADE (Block Signal Custom) modular signal system board
paragraph=The Block Signal Custom is a platform for building complex model railroad signal interlocking plants that are compatible with the open Modular Signal System standard.
category=Device Control
url=https://docs.iascaled.com/SimpleSig/Block%20Signal%20Custom/developer_guide/
architectures=*
includes=mss-xcade.h
